# Generated by Django 5.2.5 on 2025-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
